In [6]:
import pandas as pd
df = pd.read_excel("../data/stock_market_india_commercial_seo_with_content.xlsx")

In [8]:
df.head()

,Keyword,URL,Title,H1,H2,H3,Word_Count,Estimated_Backlinks,Domain,Content
0,best trading app in india 2024,https://zerodha.com/best-trading-app-in-india-...,Best Trading App In India 2024 | Zerodha,Best Trading App In India 2024,Features of best trading app in india 2024,How to start with best trading app in india 2024,1878,3195,zerodha.com,Looking for best trading app in india 2024? Th...
1,best trading app in india 2024,https://groww.in/best-trading-app-in-india-2024,Best Trading App In India 2024 | Groww,Best Trading App In India 2024,Features of best trading app in india 2024,How to start with best trading app in india 2024,2802,429,groww.in,Looking for best trading app in india 2024? Th...
2,best trading app in india 2024,https://upstox.com/best-trading-app-in-india-2024,Best Trading App In India 2024 | Upstox,Best Trading App In India 2024,Features of best trading app in india 2024,How to start with best trading app in india 2024,2487,850,upstox.com,Looking for best trading app in india 2024? Th...
3,best trading app in india 2024,https://angelone.in/best-trading-app-in-india-...,Best Trading App In India 2024 | Angelone,Best Trading App In India 2024,Features of best trading app in india 2024,How to start with best trading app in india 2024,2797,3104,angelone.in,Looking for best trading app in india 2024? Th...
4,best trading app in india 2024,https://5paisa.com/best-trading-app-in-india-2024,Best Trading App In India 2024 | 5Paisa,Best Trading App In India 2024,Features of best trading app in india 2024,How to start with best trading app in india 2024,1825,4519,5paisa.com,Looking for best trading app in india 2024? Th...

In [9]:
df.isnull().any()

Keyword                False
URL                    False
Title                  False
H1                     False
H2                     False
H3                     False
Word_Count             False
Estimated_Backlinks    False
Domain                 False
Content                False
dtype: bool

In [10]:
df.duplicated().any()

np.False_

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Keyword              1000 non-null   object
 1   URL                  1000 non-null   object
 2   Title                1000 non-null   object
 3   H1                   1000 non-null   object
 4   H2                   1000 non-null   object
 5   H3                   1000 non-null   object
 6   Word_Count           1000 non-null   int64
 7   Estimated_Backlinks  1000 non-null   int64
 8   Domain               1000 non-null   object
 9   Content              1000 non-null   object
dtypes: int64(2), object(8)
memory usage: 78.2+ KB

In [14]:
for col in df.columns:
    print(f"\nColumn: {col}")
    print("Unique values:", df[col].nunique())
    print(df[col].value_counts(dropna=False))

Column: Keyword
Unique values: 100
Keyword
best trading app in india 2024                 10
best demat account in india 2024               10
lowest brokerage trading account india 2024    10
open demat account online 2024                 10
intraday trading app india 2024                10
                                               ..
stocks investment platform india 2033          10
futures and options broker india 2033          10
discount broker india 2033                     10
best stock broker for beginners india 2033     10
online share trading account 2033              10
Name: count, Length: 100, dtype: int64

Column: URL
Unique values: 1000
URL
https://kotaksecurities.com/online-share-trading-account-2033    1
https://zerodha.com/best-trading-app-in-india-2024               1
https://groww.in/best-trading-app-in-india-2024                  1
https://upstox.com/best-trading-app-in-india-2024                1
https://angelone.in/best-trading-app-in-india-2024               1
                                                                ..
https://upstox.com/best-demat-account-in-india-2024              1
https://groww.in/best-demat-account-in-india-2024                1
https://zerodha.com/best-demat-account-in-india-2024             1
https://kotaksecurities.com/best-trading-app-in-india-2024       1
https://sharekhan.com/best-trading-app-in-india-2024             1
Name: count, Length: 1000, dtype: int64

Column: Title
Unique values: 1000
Title
Online Share Trading Account 2033 | Kotaksecurities    1
Best Trading App In India 2024 | Zerodha               1
Best Trading App In India 2024 | Groww                 1
Best Trading App In India 2024 | Upstox                1
Best Trading App In India 2024 | Angelone              1
                                                      ..
Best Demat Account In India 2024 | Upstox              1
Best Demat Account In India 2024 | Groww               1
Best Demat Account In India 2024 | Zerodha             1
Best Trading App In India 2024 | Kotaksecurities       1
Best Trading App In India 2024 | Sharekhan             1
Name: count, Length: 1000, dtype: int64

Column: H1
Unique values: 100
H1
Best Trading App In India 2024                 10
Best Demat Account In India 2024               10
Lowest Brokerage Trading Account India 2024    10
Open Demat Account Online 2024                 10
Intraday Trading App India 2024                10
                                               ..
Stocks Investment Platform India 2033          10
Futures And Options Broker India 2033          10
Discount Broker India 2033                     10
Best Stock Broker For Beginners India 2033     10
Online Share Trading Account 2033              10
Name: count, Length: 100, dtype: int64

Column: H2
Unique values: 100
H2
Features of best trading app in india 2024                 10
Features of best demat account in india 2024               10
Features of lowest brokerage trading account india 2024    10
Features of open demat account online 2024                 10
Features of intraday trading app india 2024                10
                                                           ..
Features of stocks investment platform india 2033          10
Features of futures and options broker india 2033          10
Features of discount broker india 2033                     10
Features of best stock broker for beginners india 2033     10
Features of online share trading account 2033              10
Name: count, Length: 100, dtype: int64

Column: H3
Unique values: 100
H3
How to start with best trading app in india 2024                 10
How to start with best demat account in india 2024               10
How to start with lowest brokerage trading account india 2024    10
How to start with open demat account online 2024                 10
How to start with intraday trading app india 2024                10
                                                                 ..
How to start with stocks investment platform india 2033          10
How to start with futures and options broker india 2033          10
How to start with discount broker india 2033                     10
How to start with best stock broker for beginners india 2033     10
How to start with online share trading account 2033              10
Name: count, Length: 100, dtype: int64

Column: Word_Count
Unique values: 806
Word_Count
1566    4
847     4
2308    3
2675    3
1367    3
       ..
874     1
1108    1
2427    1
2772    1
1283    1
Name: count, Length: 806, dtype: int64

Column: Estimated_Backlinks
Unique values: 901
Estimated_Backlinks
632     4
2396    3
3415    3
4063    3
650     3
       ..
399     1
1667    1
4592    1
2375    1
3104    1
Name: count, Length: 901, dtype: int64

Column: Domain
Unique values: 10
Domain
zerodha.com            100
groww.in               100
upstox.com             100
angelone.in            100
5paisa.com             100
icicidirect.com        100
hdfcsec.com            100
motilaloswal.com       100
sharekhan.com          100
kotaksecurities.com    100
Name: count, dtype: int64

Column: Content
Unique values: 1000
Content
Looking for online share trading account 2033? This page on kotaksecurities.com explains brokerage charges, account opening process, platform features, margin benefits, and why it is suitable for beginners and active traders in India. Compare fees, tools, research support, and mobile trading experience before choosing the right stock broker.    1
Looking for best trading app in india 2024? This page on zerodha.com explains brokerage charges, account opening process, platform features, margin benefits, and why it is suitable for beginners and active traders in India. Compare fees, tools, research support, and mobile trading experience before choosing the right stock broker.               1
Looking for best trading app in india 2024? This page on groww.in explains brokerage charges, account opening process, platform features, margin benefits, and why it is suitable for beginners and active traders in India. Compare fees, tools, research support, and mobile trading experience before choosing the right stock broker.                  1
Looking for best trading app in india 2024? This page on upstox.com explains brokerage charges, account opening process, platform features, margin benefits, and why it is suitable for beginners and active traders in India. Compare fees, tools, research support, and mobile trading experience before choosing the right stock broker.                1
Looking for best trading app in india 2024? This page on angelone.in explains brokerage charges, account opening process, platform features, margin benefits, and why it is suitable for beginners and active traders in India. Compare fees, tools, research support, and mobile trading experience before choosing the right stock broker.               1
                                                                                                                                                                                                                                                                                                                                                          ..
Looking for best demat account in india 2024? This page on upstox.com explains brokerage charges, account opening process, platform features, margin benefits, and why it is suitable for beginners and active traders in India. Compare fees, tools, research support, and mobile trading experience before choosing the right stock broker.              1
Looking for best demat account in india 2024? This page on groww.in explains brokerage charges, account opening process, platform features, margin benefits, and why it is suitable for beginners and active traders in India. Compare fees, tools, research support, and mobile trading experience before choosing the right stock broker.                1
Looking for best demat account in india 2024? This page on zerodha.com explains brokerage charges, account opening process, platform features, margin benefits, and why it is suitable for beginners and active traders in India. Compare fees, tools, research support, and mobile trading experience before choosing the right stock broker.             1
Looking for best trading app in india 2024? This page on kotaksecurities.com explains brokerage charges, account opening process, platform features, margin benefits, and why it is suitable for beginners and active traders in India. Compare fees, tools, research support, and mobile trading experience before choosing the right stock broker.       1
Looking for best trading app in india 2024? This page on sharekhan.com explains brokerage charges, account opening process, platform features, margin benefits, and why it is suitable for beginners and active traders in India. Compare fees, tools, research support, and mobile trading experience before choosing the right stock broker.             1
Name: count, Length: 1000, dtype: int64

In [15]:
summary = pd.DataFrame({
    "unique_count": df.nunique(),
    "total_count": df.count()
})

summary

                     unique_count  total_count
Keyword                       100         1000
URL                          1000         1000
Title                        1000         1000
H1                            100         1000
H2                            100         1000
H3                            100         1000
Word_Count                    806         1000
Estimated_Backlinks           901         1000
Domain                         10         1000
Content                      1000         1000

In [17]:
categorical_columns = df.select_dtypes(include = ['category','object']).columns
categorical_columns

Index(['Keyword', 'URL', 'Title', 'H1', 'H2', 'H3', 'Domain', 'Content'], dtype='object')